Update default params based on tuning search space
aimclub/Fedot.Industrial pull request #137
Opened 2024-05-14 08:52 UTC by PvtKaefsky

Checked all parameters with those taken into account in the selection of parameters during tuning (tuning/search_space.py).

For new continuous values took average values from those specified in the tuning search space selection.

For the rest I checked the documentation somewhere, somewhere I set them by analogy with similar classes.

2024-05-14 11:23 UTC, technocreep requested changes
отметил что успел из явных недочётов. Дальше предлагаю самостоятельно проверить себя

2024-05-14 11:23 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "activation": "softmax"
тут вроде не хватает num_classes

2024-05-14 12:49 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
n_jobs тут был изначально, убрать?

И вообще тут ситуация в том, что topological_extractor указан два раза в search space: один раз в industrial_search_space, а другой раз в parameters_per_operation. И получается что в данном случае учитываются параметры обоих. Как тут лучше сделать, оставить только два параметра для industrial_search_space?

2024-05-14 12:51 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "spectrum_type": "smoothed",
убрал spectrum_type из дефолта, approximation в атрибутах класса и так зафиксирован

2024-05-14 12:54 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "var_threshold": 0.01,
убрал window_mode и var_threshold, длину окна поставил 0 (до этого стояло среднее области поиска)

2024-05-14 13:04 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "SPD_metric": "riemann"
апдейтнул имена атрибутов класса riemann_extractor в соответствии с именами параметров

2024-05-14 13:06 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "window_mode": true,
тут тоже это было изначально

2024-05-14 13:18 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +  },
убрал channel_filtration из дефолта и поиска

2024-05-14 13:28 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "num_features": 10000
не совсем понял, что тут нужно исправить? добавить дефолтные параметры для base_extractor или что?

2024-05-14 13:39 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +  },
а из какого класса взяты эти атрибуты? не нахожу их ни в inception, ни в base_nn

2024-05-14 13:46 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "activation": "softmax"
не нашел такого атрибута в классе, в search space тоже нету такого параметра

2024-05-14 13:54 UTC, pep8speaks commented
Thanks for update, @PvtKaefsky! 



* In the file [`fedot_ind/core/models/recurrence/reccurence_extractor.py`](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/models/recurrence/reccurence_extractor.py):

> [Line 8:1](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/models/recurrence/reccurence_extractor.py#L8): [F403](https://duckduckgo.com/?q=pep8%20F403) 'from fedot_ind.core.metrics.metrics_implementation import *' used; unable to detect undefined names
> [Line 8:1](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/models/recurrence/reccurence_extractor.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot_ind.core.metrics.metrics_implementation.*' imported but unused
> [Line 48:61](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/models/recurrence/reccurence_extractor.py#L48): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

* In the file [`fedot_ind/core/tuning/search_space.py`](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py):

> [Line 5:1](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L5): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot_ind.core.repository.constanst_repository.DISTANCE_METRICS' imported but unused
> [Line 101:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L101): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 135:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L135): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 151:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L151): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 173:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L173): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 179:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L179): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 185:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L185): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 203:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L203): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 221:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L221): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 251:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L251): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 269:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L269): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 283:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L283): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 301:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L301): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 315:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L315): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 329:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L329): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 343:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L343): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 357:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L357): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 375:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L375): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 391:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L391): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 400:38](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L400): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 406:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L406): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 428:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L428): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 453:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L453): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 495:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L495): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 511:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot_ind/core/tuning/search_space.py#L511): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 517:9](https://github.com/aimclub/Fedot.Industrial/blob/ceb30cda6d87e410c3ad4a7e1964df420a407b15/fedot [...]

2024-05-15 09:10 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "var_threshold": 0.01,
если посмотреть по коду, то var_threshold вообще не используется нигде, поэтому его можно убрать отовсюду, я полагаю. По крайней мере я не нашёл упоминаний, проверь ещё разок, я могу ошибаться

2024-05-15 09:23 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "var_threshold": 0.01,
> длину окна поставил 0

если так, то из search_space надо это значение убрать – искать оптимум, начиная от 1
объясню, почему: дефолтные параметры используются для самого первого фита пайплайна и предикта. Оптимизатор хранит результаты предикта как бейзлайн. В ходе оптимизации выбираются другие комбинации параметров, благодаря чему получаются иные результаты, которые сравниваются с тем самым бейзлайном и, если они хуже, по итогу на руках у нас остаётся модель с дефолтными параметрами (да, такое бывает)

страйд при окне=0 влияния не оказывает, это и логично. Страйд - это шаг, с которым окно перемещается вдоль временного ряда. Если окно=0, то мы берём ряд целиком – некуда шагать

2024-05-15 09:24 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "var_threshold": 0.01,
еще важное уточнение для понимания: window_size тут – процент от длины окна

2024-05-15 09:33 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "sv_selector": "median",
> sv_selector тут был изначально указан, убрать?
> 
> rank_regularization учтен ниже

да, из спэйса убрать

в классе есть low_rank_approximation и tensor_approximation, которые из OperationParameters приходят, поэтому это надо добавить в search_space и default

2024-05-15 09:35 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "spectrum_type": "smoothed",
> убрал spectrum_type из дефолта, approximation в атрибутах класса и так зафиксирован

значит надо сделать self.approximation = 'smooth'

2024-05-15 09:37 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
n_jobs убрать

2024-05-15 09:41 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "window_mode": true,
для рекуррентного 
- из default убрать     "window_mode": true,    "min_signal_ratio": 0.5,    "max_signal_ratio": 0.75,
- "rec_metric" в search space раскомментровать, оставить две опции: cosine и euclidean

2024-05-15 09:43 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +  },
комментарий про signal extractor, причём тут channel_filtration

2024-05-15 09:46 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +  },
так что верни

2024-05-15 09:49 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "num_features": 10000
сорян, тут зря быканул, забудь

2024-05-16 09:21 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "sv_selector": "median",
При tensor_approximation: true пайплайн крашится на инициализации, может тогда не стоит добавлять этот параметр в search_space?

2024-05-16 09:38 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
А что по поводу того, что в search_space он два раза учитывается?

Я так понимаю, лучше убрать его из parameters_per_operation и убрать те параметры, которых нету в атрибутах класса?

2024-05-16 10:17 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
И в целом для проверки topological_extractor не получилось запустить рекомендованный в классе пайплайн (eigen_basis + topological_extractor + rf) ни с какими параметрами.

2024-05-16 10:30 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "window_mode": true,
Убрал неиспользуемые параметры, rec_metric поправил

Тут еще заметил, что в тюнинге window_size начинается с 5 при дефолтном значении в 0. Это стоит исправлять или без разницы, т.к. шаг всё равно 5?

2024-05-16 10:32 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +  },
Исправил, signal_extractor убрал

2024-05-16 11:02 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "sv_selector": "median",
tensor_approximation не добавляем, согласен

2024-05-16 11:09 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "activation": "softmax"
Проверил эти варианты, разницы не заметил

2024-05-16 11:13 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "sv_selector": "median",
stride давай пока не удалять. ПОхоже он действительно не используется на данный момент, хотя должен, как я понимаю

[вот тут есть основной метод](https://github.com/ITMO-NSS-team/Fedot.Industrial/blob/a2489dba4badc76ab7b03791bd30a0002ef2c073/fedot_ind/core/operation/transformation/basis/eigen_basis.py#L175), в котором формируется ганкелева матрица – это база 

так вот этот класс HankelMatrix может принимать stride, посмотри сам

поэтому оставим как есть, но на следующем этапе займёмся прокидыванием этого параметра в HankelMatrix. Да, это легко, но это просто совсем другая история

2024-05-16 11:16 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
parameters_per_operation лучше не трогать

2024-05-16 11:17 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
пока просто убрать n_jobs

2024-05-16 11:26 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
в чём проблема с запуском? у меня получилось запустить
![image](https://github.com/aimclub/Fedot.Industrial/assets/44948116/5aaf1bcc-bdc2-4971-a878-9aede5a9932b)

2024-05-16 11:34 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "window_mode": true,
я бы для рекуррентного в default_parameters поставил окно = 0

2024-05-16 11:35 UTC, technocreep commented on fedot_ind/core/repository/data/default_operation_params.json
> +  },
исправления пуш сразу в ветку, иначе я ж не виже

2024-05-16 11:55 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "n_jobs": 2,
Тюнер также работает, но на фите падает

2024-05-16 12:12 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "activation": "softmax"
Добавил

2024-05-16 12:13 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +  },
Тут я пока что добавил в дефолт, но проверить пока не получается, тоже на фите падает при любых параметрах

2024-05-16 12:25 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "var_threshold": 0.01,
Поставил в search_space поиск длины окна от 5 с шагом в 5 по аналогии с другими экстракторами

2024-05-16 12:25 UTC, PvtKaefsky commented on fedot_ind/core/repository/data/default_operation_params.json
> +    "spectrum_type": "smoothed",
Добавил

2024-05-17 11:49 UTC, merged