add anomaly detection algorithms
aimclub/Fedot.Industrial pull request #146
Opened 2024-05-27 14:21 UTC by Lopa10ko

2024-05-27 14:22 UTC, pep8speaks commented
@Lopa10ko, my friend! There is something you should fix. 







* In the file [`fedot_ind/api/main.py`](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/api/main.py):

> [Line 492:17](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/api/main.py#L492): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders
> [Line 494:17](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/api/main.py#L494): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders



* In the file [`fedot_ind/core/architecture/pipelines/abstract_pipeline.py`](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/architecture/pipelines/abstract_pipeline.py):

> [Line 188:121](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/architecture/pipelines/abstract_pipeline.py#L188): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 189:121](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/architecture/pipelines/abstract_pipeline.py#L189): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)



* In the file [`fedot_ind/core/metrics/anomaly_detection/function.py`](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/anomaly_detection/function.py):

> [Line 64:121](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/anomaly_detection/function.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 100:17](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/anomaly_detection/function.py#L100): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 163:48](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/anomaly_detection/function.py#L163): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 177:94](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/anomaly_detection/function.py#L177): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 259:63](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/anomaly_detection/function.py#L259): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 314:9](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/anomaly_detection/function.py#L314): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'scale_func' is assigned to but never used

* In the file [`fedot_ind/core/metrics/metrics_implementation.py`](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py):

> [Line 17:1](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L17): [F811](https://duckduckgo.com/?q=pep8%20F811) redefinition of unused 'np' from line 4
> [Line 56:26](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L56): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 92:16](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L92): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 93:76](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L93): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 247:47](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L247): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 273:47](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L273): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 284:17](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L284): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 299:1](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L299): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 552:59](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L552): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 553:59](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/metrics/metrics_implementation.py#L553): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

* In the file [`fedot_ind/core/models/detection/anomaly/algorithms/convolutional_autoencoder.py`](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/convolutional_autoencoder.py):

> [Line 22:1](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/convolutional_autoencoder.py#L22): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 50:1](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/convolutional_autoencoder.py#L50): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 60:1](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/convolutional_autoencoder.py#L60): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 90:1](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/convolutional_autoencoder.py#L90): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`fedot_ind/core/models/detection/anomaly/algorithms/isolation_forest.py`](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/isolation_forest.py):

> [Line 14:1](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/isolation_forest.py#L14): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`fedot_ind/core/models/detection/anomaly/algorithms/lstm_autoencoder.py`](https://github.com/aimclub/Fedot.Industrial/blob/136e10ed5c53cee7cfeab2e0104c38e3b2b6c0f3/fedot_ind/core/models/detection/anomaly/algorithms/lstm_autoencoder.p [...]

2024-06-10 07:03 UTC, v1docq approved these changes

2024-06-10 11:16 UTC, technocreep requested changes
работа проделана колоссальная, это круто

но я бы отметил следующее:

1. Примеры лучше оформить в виде ноутбуков. Иначе к ним нельзя даже никого отослать, чтобы потенциальный пользователь изучил принцип работы.

2. Мы в примерах используем `industrial_forecasting_modelling_loop`, `industrial_common_modelling_loop`. Если предполагается, что кто-то будет этим пользоваться, типа для упрощения проведения экспериментов, то я бы поработал над нэйминогом. Если это один из основных инструментов, то его импорт – неудобен

3. Классно, что добавилось столько алго для детектирования. Будет ещё круче, если к каждому из них добавится по самому простому юниту. На примере [PR по DeepAR](https://github.com/aimclub/Fedot.Industrial/pull/150/commits/1f2fdd76a0dcd5221e17f1211baa1f6827b834de), можно понять, зачем это делать

4. Надо проверить работу созданных примеров: в одном случае валятся ошибки, в другом – нет исходных данных

2024-06-10 11:16 UTC, technocreep commented on examples/automl_example/api_example/time_series/ts_anomaly_detection/ts_anomaly_detection_example.py
этот пример валится с ошибкой `ValueError: Initial pipeline fit was failed due to: 45. Check pipeline structure and the correctness of the data
`

2024-06-10 11:16 UTC, technocreep commented on examples/automl_example/api_example/time_series/ts_anomaly_detection/ts_anomaly_detection_example.py
> +    metric_names = ('accuracy')
можно выбрать что-то одно

2024-06-10 11:16 UTC, technocreep commented on examples/automl_example/api_example/time_series/ts_anomaly_detection/ts_anomaly_detection_example.py
> +        with_tunig=False,
with_tunig ?

2024-06-10 11:16 UTC, technocreep commented on fedot_ind/core/operation/decomposition/matrix_decomposition/column_sampling_decomposition.py
> +        # plt.show()
этот метод, видимо, можно урать

2024-06-10 11:28 UTC, Lopa10ko commented on examples/automl_example/api_example/time_series/ts_anomaly_detection/ts_anomaly_detection_example.py
> +    metric_names = ('accuracy')
[29cf509](https://github.com/aimclub/Fedot.Industrial/pull/146/commits/29cf509e98af0152ba7eeeb77183210a1d3e6a5c)

2024-06-10 11:28 UTC, Lopa10ko commented on examples/automl_example/api_example/time_series/ts_anomaly_detection/ts_anomaly_detection_example.py
> +        with_tunig=False,
[29cf509](https://github.com/aimclub/Fedot.Industrial/pull/146/commits/29cf509e98af0152ba7eeeb77183210a1d3e6a5c)

2024-06-10 12:06 UTC, Lopa10ko commented on fedot_ind/core/models/detection/custom/stat_detector.py
> +    """
[9e337f7](https://github.com/aimclub/Fedot.Industrial/pull/146/commits/9e337f71ccab9d78dfe14ac57c37618b6a973363)
[4eb6a4b](https://github.com/aimclub/Fedot.Industrial/pull/146/commits/4eb6a4b5961ab335ed6e611f4a33c17ad2e585db)

2024-06-10 12:08 UTC, Lopa10ko commented on fedot_ind/core/models/algebra/__init__.py
эту директорию предполагалось использовать для организации композитных моделей из существующих детекторов

2024-06-10 12:10 UTC, technocreep commented on fedot_ind/core/models/algebra/__init__.py
>> предполагалось

то есть нужна или нет?

2024-06-10 12:12 UTC, Lopa10ko commented on fedot_ind/core/operation/decomposition/matrix_decomposition/column_sampling_decomposition.py
> +        # plt.show()
[440bfe8](https://github.com/aimclub/Fedot.Industrial/pull/146/commits/440bfe88139913371b6354ad5042b4b72dadb9c5)

2024-06-10 12:15 UTC, Lopa10ko commented on examples/data/detection/data/Load data.ipynb
[196f729](https://github.com/aimclub/Fedot.Industrial/pull/146/commits/196f729476cc99c66f1eb787ddc392818166a1bd)

2024-06-10 13:12 UTC, v1docq commented on examples/automl_example/api_example/time_series/ts_anomaly_detection/custom_liman_example.py
> +    train_data = [
Удалю, это кастомный вариант

2024-06-10 13:13 UTC, v1docq commented on tests/unit/models/anomaly_detection_pipelines.py
> +TASK = 'classification'
Здесь да согласен. Но пока не вижу другого выхода, тк в базовом федоте задавать самому "типы задач" весьма геморно.

2024-06-10 13:13 UTC, v1docq commented on fedot_ind/core/models/detection/custom/topo_detector.py
Не нужен, уберу

2024-06-10 13:14 UTC, v1docq commented on examples/automl_example/api_example/time_series/ts_anomaly_detection/ts_anomaly_detection_example.py
Проверю

2024-06-10 13:15 UTC, v1docq commented
> работа проделана колоссальная, это круто
> 
> но я бы отметил следующее:
> 
> 1. Примеры лучше оформить в виде ноутбуков. Иначе к ним нельзя даже никого отослать, чтобы потенциальный пользователь изучил принцип работы.
> 2. Мы в примерах используем `industrial_forecasting_modelling_loop`, `industrial_common_modelling_loop`. Если предполагается, что кто-то будет этим пользоваться, типа для упрощения проведения экспериментов, то я бы поработал над нэйминогом. Если это один из основных инструментов, то его импорт – неудобен
> 3. Классно, что добавилось столько алго для детектирования. Будет ещё круче, если к каждому из них добавится по самому простому юниту. На примере [PR по DeepAR](https://github.com/aimclub/Fedot.Industrial/pull/150/commits/1f2fdd76a0dcd5221e17f1211baa1f6827b834de), можно понять, зачем это делать
> 4. Надо проверить работу созданных примеров: в одном случае валятся ошибки, в другом – нет исходных данных

1. Можно на стажеров оформить таску.
2. Подумаю как это отрефакторить
3. В процессе
4. Правим

2024-07-04 11:32 UTC, closed without merging