TCN Model Implementation
aimclub/Fedot.Industrial pull request #151
Opened 2024-06-07 14:29 UTC by PvtKaefsky

TCN model implementation for time series forecasting

2024-06-07 14:29 UTC, pep8speaks commented
@PvtKaefsky, my friend! There is something you should fix. 

* In the file [`fedot_ind/core/models/nn/network_impl/deep_tcn.py`](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py):

> [Line 28:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L28): [F811](https://duckduckgo.com/?q=pep8%20F811) redefinition of unused 'convert_inputdata_to_torch_time_series_dataset' from line 19
> [Line 32:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L32): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 85:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L85): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 141:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L141): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 155:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L155): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 186:71](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L186): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 214:79](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L214): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 307:48](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L307): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 309:48](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L309): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 310:71](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L310): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 357:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L357): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 360:41](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L360): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 361:41](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L361): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 384:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L384): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 386:78](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L386): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 391:49](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/deep_tcn.py#L391): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py`](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py):

> [Line 1:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'warnings' imported but unused
> [Line 5:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L5): [F401](https://duckduckgo.com/?q=pep8%20F401) 'pandas as pd' imported but unused
> [Line 6:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'torch' imported but unused
> [Line 7:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L7): [F401](https://duckduckgo.com/?q=pep8%20F401) 'torch.utils.data' imported but unused
> [Line 8:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.data.data.InputData' imported but unused
> [Line 8:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.data.data.OutputData' imported but unused
> [Line 9:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L9): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.data.data_split.train_test_data_setup' imported but unused
> [Line 10:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L10): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.operations.evaluation.operation_implementations.data_operations.ts_transformations.transform_features_and_target_into_lagged' imported but unused
> [Line 13:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L13): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.repository.dataset_types.DataTypesEnum' imported but unused
> [Line 14:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.repository.tasks.Task' imported but unused
> [Line 14:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.repository.tasks.TaskTypesEnum' imported but unused
> [Line 14:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.repository.tasks.TsForecastingParams' imported but unused
> [Line 15:1](https://github.com/aimclub/Fedot.Industrial/blob/bd9a3038277980d04eb7a04b5344402ff3e8de8c/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L15): [F401](https://duckduck [...]

2024-06-10 11:28 UTC, technocreep requested changes

2024-06-10 11:28 UTC, technocreep commented on fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py
> +        self.dilation_base = dilation_base
этот класс очень похож на [этот](https://github.com/ITMO-NSS-team/Fedot.Industrial/blob/18cf9bed20a18fc22f3de8d2275bd4effe278232/fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py#L11)

2024-06-10 11:28 UTC, technocreep commented on fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py
> +                 target_length: int,
это тоже копия из deep_tcn или наоборот. Лучше оставить что-то одно

2024-06-10 11:28 UTC, technocreep commented on fedot_ind/core/models/nn/network_impl/temporal_convolution_model.py
> +        self.dilation_base = dilation_base
я так понял, что этот модуль вообще лишний, раз его нет в model_repository

2024-06-10 11:31 UTC, technocreep commented
также не увидел новых юнитов для новых модулей

2024-06-12 16:27 UTC, PvtKaefsky commented
> также не увидел новых юнитов для новых модулей

Добавил модель в в репо пайплайнов и в юнит-тест пайплайнов, также поправил его работу (до этого он был выключен):
- Починил лоадер М4, теперь он корректно парсит скачанный датасет
- Проверил тесты пайплайнов: пара моделей отказалась работать (topological_lgbm -- ошибка из-за подачи одномерных данных, composite_reg -- слишком долго работает (>5 минут). Остальное отработало нормально.

2024-06-12 17:07 UTC, Lopa10ko commented
> - Проверил тесты пайплайнов: пара моделей отказалась работать (topological_lgbm -- ошибка из-за подачи одномерных данных, composite_reg -- слишком долго работает (>5 минут). Остальное отработало нормально. 

тесты пайплайнов планируется чинить на ветке release_0.4.3_anomaly_detection_and_random_sampling, так что нужно будет обратить на это внимание во избежание конфликтов при последовательном мердже реквестов, тем более эти тесты были немного переписаны на параметризованную версию (8d3bfa8)

можно работать внутри #146, если появятся идеи фиксов для topological_* пайплайнов

2024-06-12 21:10 UTC, PvtKaefsky commented
> также не увидел новых юнитов для новых модулей

Добавил юнит тест основных функций модели

2024-06-13 10:14 UTC, technocreep approved these changes
🍻 good job

вливаю

2024-06-13 10:15 UTC, merged