change_point_detection_docs
aimclub/Fedot.Industrial pull request #42
Opened 2022-11-29 21:39 UTC by GishB

First look at Sphynx module and experiment with change_point_detection_example.rst

2022-11-30 11:41 UTC, technocreep requested changes
Красиво сделано, молодец! замечения поместил в комментарии. Продолжай в эту же ветку доставлять документацию по остальным разделам

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
здесь вот в конце не хватает раздела или подраздела, как угодно, который содержал бы полный код от и до, обычно так делается в хороших  туториалах

хорошо, что ты всё по полочкам разбираешь, но кому охота копировать блок за блоком

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
я не вижу большого смысла использовать такое название для ссылки на датасет – ``aa564g_first``

кажется, достаточно каноничного ``df``. К тому же, это растягивает строку и читаемость кода страдает

плюс, предлагаю разбить эту цепь на несколько выражений. Туториал должен быть максимально подробным, чтобы любой смог в течение пары минут разобраться

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +    cp_1[0] = 0
с этим нулём точно надо разобраться, возможно ошибка в коде

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
вот гляди. Ты в примере говоришь о каком-то временном ряде, но не показываешь его, хотя показывашь результаты вычислений. Это надо исправить – приводить результат вычислений и исходные данные рядом или на одном графике, в зависимости от того, как лучше видно. 

Также отмечу, что легенда у графиков расположена не совсем удачным образом – она сливается с самим изображением. Передвинь, плиз, её вниз, например

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
вот тут, на будущее: можно будет добавить ссылку на SST алгоритм, когда напишешь про него в документации – будет круто

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
тут тоже, может быть получится разбить громадное выражение на пару небольших?

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
я бы переписал чуть проще: First, you need to define the oil well we are working with.

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
``Workflow....`` – заголовок, а ``1. First we ....`` – не заголовок. Соответственно первое слева в меню отображается, а второе нет, хотя не логике должно быть наоборот

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +Just to be sure that it was done in a right way.
а как мы убедились? в чём убедительность картинки? надо пояснить

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
сначала ты говоришь ``Define your time series and set hypeparameters via WindowSizeSelection class.``, а потом ещё и настоятельно рекомендуешь) второе, наверное, можно заменить на пояснение, почему ЭТО надо использовать, в чём поинт

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
сначала ты говоришь, что используешь WindowSizeSelection, а потом снова его рекомендуешь. Вот рекомендацию, я думаю, можно заменить на пояснение, почему ты предлагаешь это использовать

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
вот в этом блоке кода можно попробовать укоротить строку. Например, расположить аргументы друг под другом

2022-11-30 11:41 UTC, technocreep commented on docs/source/examples/change_point_detection_example.rst
> +
как разберёшься с багом – надо будет не забыть убрать

2022-12-08 00:56 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Убрал. В классе затычку поставил типа score + [0] на выводе

2022-12-08 00:57 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +    cp_1[0] = 0
Удалил его. Ошибка в коде

2022-12-08 01:10 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
dataframe = df. Исправил

2022-12-08 01:11 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
aa564g - Название скважины из df. Это для пояснения с чем работаем тут

2022-12-08 01:38 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Исправил

2022-12-08 01:56 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Поставил

2022-12-08 01:57 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Я изменил длину строчек dataframe = df. Теперь оно не громадное)

2022-12-10 21:41 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Это комментарий к 4 блоку. Тут в целом речь идет о проверки проделанного Feature Engineering на адекватность. Дополнил словами:

The right way is to have some change point labels according to time series changes (look at the picture below)

2022-12-10 21:49 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Честно, не понял что значит укоротить строку в данном примере.

Возможно имеется ввиду привести строчки в такой вид:

text = some_function_long(hyperparamets_1, hypeparameters_2, false, ts = time_series)
text_2 = some_function_long(hyperparamets_1, hypeparameters_2, false, ts = time_series)

2022-12-10 22:16 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Исправил, теперь заголовок отражает на 3 уровне пронумерованные пункты для детектирования change points

2022-12-10 22:16 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +Just to be sure that it was done in a right way.
Пояснил ниже

2022-12-10 22:37 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
Переписал.

**Note:** Highly recommended to use WindowSizeSelection class to choose appropriate SST hypeparameters. Moreover, it is recommended to use 'summary_statistics_subsequences' as the fastest algorithm implementation for window size selection.


Define your time series and set hypeparameters via `WindowSizeSelection class`_. In the end use SingularSpectrumTransformation to detect change point scores in the time series.

2022-12-10 22:38 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +
В пункте теперь встречается ссылка на SST module и WSS Algorithm module

2022-12-10 23:28 UTC, GishB commented on docs/source/API/models_cpd/singular_spectrum_transformation.rst
> +.. autoclass:: core.cases.anomaly_detection.SSTdetector
Автосборка почему-то не работает - что-то делаю не правильно?

2022-12-10 23:29 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +.. _SST algorithm: #change_point_detection
Как указать ссылку к файлу html который бы на отдельной странице раскрыл подробную информацию?

2022-12-10 23:30 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score + [0]  # anomaly
Странная аномалия - не стал ничего больше менять в коде кроме вывода функции _score_offline.

2022-12-12 19:45 UTC, GishB commented
Running Sphinx v5.2.3
loading pickled environment... done
[autosummary] generating autosummary for: API\data_loader_api.rst, API\index.rst
, API\industrial_api.rst, API\logger_api.rst, API\models_cpd\classification_mode
ls_api.rst, API\models_cpd\decomposed_conv_api.rst, API\models_cpd\singular_spec
trum_transformation.rst, API\models_cpd\window_selection.rst, API\models_tsc\ens
emble_runner_api.rst, API\models_tsc\error_correction_api.rst, ..., examples\obj
ect_detection_example.rst, examples\ts_classification_example.rst, faq.rst, inde
x.rst, introduction\architecture.rst, introduction\index.rst, introduction\indus
trial.rst, introduction\installation.rst, introduction\license.rst, introduction
\quickstart.rst
Failed to import core.your.first.script.path.
Possible hints:
* AttributeError: module 'core' has no attribute 'your'
* ModuleNotFoundError: No module named 'core.your'
Failed to import core.models.cnn.classification_models.
Possible hints:
* ModuleNotFoundError: No module named 'torchvision'
* AttributeError: module 'core.models.cnn' has no attribute 'classification_mode
ls'
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 3 changed, 0 removed
reading sources... [100%] API/models_cpd/window_selection
WARNING: autodoc: failed to import module 'classification_models' from module 'c
ore.models.cnn'; the following exception was raised:
No module named 'torchvision'
WARNING: autodoc: failed to import class 'anomaly_detection.SSTdetector.Singular
SpectrumTransformation' from module 'cases'; the following exception was raised:
No module named 'cases.anomaly_detection'
C:\Users\1\Desktop\GitHub\Fedot.Industrial\cases\anomaly_detection\WSSAlgorithms
.py:docstring of WSSAlgorithms.WindowSizeSelection:22: ERROR: Unexpected indenta
tion.
C:\Users\1\Desktop\GitHub\Fedot.Industrial\cases\anomaly_detection\WSSAlgorithms
.py:docstring of WSSAlgorithms.WindowSizeSelection:31: WARNING: Definition list 
ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... C:\Users\1\Desktop\GitHub\Fedot.Industrial\docs\source\A
PI\models_cpd\singular_spectrum_transformation.rst: WARNING: document isn't incl
uded in any toctree
C:\Users\1\Desktop\GitHub\Fedot.Industrial\docs\source\API\models_cpd\window_sel
ection.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] index
generating indices... genindex done
highlighting module code... [100%] core.operation.utils.result_parser
writing additional pages... search done
copying images... [100%] ../img/fedot-industrial.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 6 warnings.

The HTML pages are in _build\html.

2022-12-12 19:46 UTC, GishB commented on docs/source/API/models_cpd/singular_spectrum_transformation.rst
> +.. autoclass:: core.cases.anomaly_detection.SSTdetector
Window Size Selection
=====================

.. autoclass:: cases.anomaly_detection.WSSAlgorithms.WindowSizeSelection
   :members:

2022-12-12 19:46 UTC, GishB commented on docs/source/examples/change_point_detection_example.rst
> +.. _SST algorithm: #change_point_detection
`:ref:ТВОЙТЕКСТ<лейбл> `

Решено

2022-12-12 19:53 UTC, GishB commented
![image](https://user-images.githubusercontent.com/90556084/207141174-b70c4093-5a29-41fc-9d4f-1a5bf80b60ec.png)

2022-12-16 14:46 UTC, GishB commented
1. Обновил change point detection example:
- Обновил изображения
- Обновил код исходя из нового расположения файлов

2. Собрал 2 страницы для SingularSpectrumTransformation и WindowSelection :
- Исправил проблемы с docstring SST модуля
- Исправил проблемы с docstring WSS

3. Собрал страницу в Fundamental info для change point detection:
- Описал логику работы модуля WindowSelection и SingularSpectrumTransformation поверхностно.
- Добавил изображения для каждого алгоритма WindowSelection

2022-12-19 13:56 UTC, GishB commented
Обновил описание к change point detection task в разделе Architecture of FEDOT.Industrial

- Изображение для задачи на примере датасета "гамма-каротажа"
- Описание шагов для решения задачи

- [ ] В следующем PR обновлю формулы для Change Point Detection в Fundamentals.info

2023-08-08 10:04 UTC, closed without merging